initial_board = (
    ('w', False, 2, 'r', False, False),('b', False, 2, 'k', False, False),('w', False, 2, 'b', False, False),('b', False, 2, 'q', False, False),('w', False, 2, 'K', False, False),('b', False, 2, 'b', False, False),('w', False, 2, 'k', False, False),('b', False, 2, 'r', False, False),
    ('b', False, 2, 'p', False, False),('w', False, 2, 'p', False, False),('b', False, 2, 'p', False, False),('w', False, 2, 'p', False, False),('b', False, 2, 'p', False, False),('w', False, 2, 'p', False, False),('b', False, 2, 'p', False, False),('w', False, 2, 'p', False, False),
    ('w', False, 0, '', False, False),('b', False, 0, '', False, False),('w', False, 0, '', False, False),('b', False, 0, '', False, False),('w', False, 0, '', False, False),('b', False, 0, '', False, False),('w', False, 0, '', False, False),('b', False, 0, '', False, False),
    ('b', False, 0, '', False, False),('w', False, 0, '', False, False),('b', False, 0, '', False, False),('w', False, 0, '', False, False),('b', False, 0, '', False, False),('w', False, 0, '', False, False),('b', False, 0, '', False, False),('w', False, 0, '', False, False),
    ('w', False, 0, '', False, False),('b', False, 0, '', False, False),('w', False, 0, '', False, False),('b', False, 0, '', False, False),('w', False, 0, '', False, False),('b', False, 0, '', False, False),('w', False, 0, '', False, False),('b', False, 0, '', False, False),
    ('b', False, 0, '', False, False),('w', False, 0, '', False, False),('b', False, 0, '', False, False),('w', False, 0, '', False, False),('b', False, 0, '', False, False),('w', False, 0, '', False, False),('b', False, 0, '', False, False),('w', False, 0, '', False, False),
    ('w', False, 1, 'p', False, False),('b', False, 1, 'p', False, False),('w', False, 1, 'p', False, False),('b', False, 1, 'p', False, False),('w', False, 1, 'p', False, False),('b', False, 1, 'p', False, False),('w', False, 1, 'p', False, False),('b', False, 1, 'p', False, False),
    ('b', False, 1, 'r', False, False),('w', False, 1, 'k', False, False),('b', False, 1, 'b', False, False),('w', False, 1, 'q', False, False),('b', False, 1, 'K', False, False),('w', False, 1, 'b', False, False),('b', False, 1, 'k', False, False),('w', False, 1, 'r', False, False),
)